[package]
name = "networking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swift-rs = { path = "./swift-rs" }

[build-dependencies]
swift-rs = { path = "./swift-rs", features = ["build"] }